---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-hello-world
  namespace: hello-world
spec:
  replicas: 4
  rabbitmq:
    additionalConfig: |
      log.console.level = info
      channel_max = 1700
      default_user= guest 
      default_pass = guest
      default_user_tags.administrator = true
  service:
    type: LoadBalancer

